package com.fime.labihc.papiromania.API;

import com.fime.labihc.papiromania.R;

public class ImgResParser {
    public static int mapImgId(int rawID){
        switch (rawID){
            default:
                return R.drawable.placeholder;
            case 1:
                return R.drawable.catego_animals;
            case 11:
                return R.drawable.inst_perro5;
            case 111:
                return R.drawable.inst_perro1;
            case 112:
                return R.drawable.inst_perro2;
            case 113:
                return R.drawable.inst_perro3;
            case 114:
                return R.drawable.inst_perro4;
            case 115:
                return R.drawable.inst_perro5;
            case 12:
                return R.drawable.inst_raton11;
            case 121:
                return R.drawable.inst_raton1;
            case 122:
                return R.drawable.inst_raton2;
            case 123:
                return R.drawable.inst_raton3;
            case 124:
                return R.drawable.inst_raton4;
            case 125:
                return R.drawable.inst_raton5;
            case 126:
                return R.drawable.inst_raton6;
            case 127:
                return R.drawable.inst_raton7;
            case 128:
                return R.drawable.inst_raton8;
            case 129:
                return R.drawable.inst_raton9;
            case 1210:
                return R.drawable.inst_raton10;
            case 1211:
                return R.drawable.inst_raton11;
            case 13:
                return R.drawable.inst_zorro7;
            case 131:
                return R.drawable.inst_zorro1;
            case 132:
                return R.drawable.inst_zorro2;
            case 133:
                return R.drawable.inst_zorro3;
            case 134:
                return R.drawable.inst_zorro4;
            case 135:
                return R.drawable.inst_zorro5;
            case 136:
                return R.drawable.inst_zorro6;
            case 137:
                return R.drawable.inst_zorro7;
            case 2:
                return R.drawable.catego_geometry;
            case 21:
                return R.drawable.inst_estrella8;
            case 211:
                return R.drawable.inst_estrella1;
            case 212:
                return R.drawable.inst_estrella2;
            case 213:
                return R.drawable.inst_estrella3;
            case 214:
                return R.drawable.inst_estrella4;
            case 215:
                return R.drawable.inst_estrella5;
            case 216:
                return R.drawable.inst_estrella6;
            case 217:
                return R.drawable.inst_estrella7;
            case 218:
                return R.drawable.inst_estrella8;
            case 22:
                return R.drawable.inst_triangulo8;
            case 221:
                return R.drawable.inst_triangulo1;
            case 222:
                return R.drawable.inst_triangulo2;
            case 223:
                return R.drawable.inst_triangulo3;
            case 224:
                return R.drawable.inst_triangulo4;
            case 225:
                return R.drawable.inst_triangulo5;
            case 226:
                return R.drawable.inst_triangulo6;
            case 227:
                return R.drawable.inst_triangulo7;
            case 228:
                return R.drawable.inst_triangulo8;
            case 23:
                return R.drawable.inst_cubo13;
            case 231:
                return R.drawable.inst_cubo1;
            case 232:
                return R.drawable.inst_cubo2;
            case 233:
                return R.drawable.inst_cubo3;
            case 234:
                return R.drawable.inst_cubo4;
            case 235:
                return R.drawable.inst_cubo5;
            case 236:
                return R.drawable.inst_cubo6;
            case 237:
                return R.drawable.inst_cubo7;
            case 238:
                return R.drawable.inst_cubo8;
            case 239:
                return R.drawable.inst_cubo9;
            case 2310:
                return R.drawable.inst_cubo10;
            case 2311:
                return R.drawable.inst_cubo11;
            case 2312:
                return R.drawable.inst_cubo12;
            case 2313:
                return R.drawable.inst_cubo13;
            case 3:
                return R.drawable.catego_flowers;
            case 31:
                return R.drawable.inst_flor10;
            case 311:
                return R.drawable.inst_flor1;
            case 312:
                return R.drawable.inst_flor2;
            case 313:
                return R.drawable.inst_flor3;
            case 314:
                return R.drawable.inst_flor4;
            case 315:
                return R.drawable.inst_flor5;
            case 316:
                return R.drawable.inst_flor6;
            case 317:
                return R.drawable.inst_flor7;
            case 318:
                return R.drawable.inst_flor8;
            case 319:
                return R.drawable.inst_flor9;
            case 3110:
                return R.drawable.inst_flor10;
            case 32:
                return R.drawable.inst_rosa8;
            case 321:
                return R.drawable.inst_rosa1;
            case 322:
                return R.drawable.inst_rosa2;
            case 323:
                return R.drawable.inst_rosa3;
            case 324:
                return R.drawable.inst_rosa4;
            case 325:
                return R.drawable.inst_rosa5;
            case 326:
                return R.drawable.inst_rosa6;
            case 327:
                return R.drawable.inst_rosa7;
            case 328:
                return R.drawable.inst_rosa8;
            case 33:
                return R.drawable.inst_tulipan8;
            case 331:
                return R.drawable.inst_tulipan1;
            case 332:
                return R.drawable.inst_tulipan2;
            case 333:
                return R.drawable.inst_tulipan3;
            case 334:
                return R.drawable.inst_tulipan4;
            case 335:
                return R.drawable.inst_tulipan5;
            case 336:
                return R.drawable.inst_tulipan6;
            case 337:
                return R.drawable.inst_tulipan7;
            case 338:
                return R.drawable.inst_tulipan8;
            case 4:
                return R.drawable.catego_others;
            case 41:
                return R.drawable.inst_helado7;
            case 411:
                return R.drawable.inst_helado1;
            case 412:
                return R.drawable.inst_helado2;
            case 413:
                return R.drawable.inst_helado3;
            case 414:
                return R.drawable.inst_helado4;
            case 415:
                return R.drawable.inst_helado5;
            case 416:
                return R.drawable.inst_helado6;
            case 417:
                return R.drawable.inst_helado7;
            case 42:
                return R.drawable.inst_molino8;
            case 421:
                return R.drawable.inst_molino1;
            case 422:
                return R.drawable.inst_molino2;
            case 423:
                return R.drawable.inst_molino3;
            case 4324:
                return R.drawable.inst_molino4;
            case 425:
                return R.drawable.inst_molino5;
            case 426:
                return R.drawable.inst_molino6;
            case 427:
                return R.drawable.inst_molino7;
            case 43:
                return R.drawable.inst_corazon7;
            case 431:
                return R.drawable.inst_corazon1;
            case 432:
                return R.drawable.inst_corazon2;
            case 433:
                return R.drawable.inst_corazon3;
            case 434:
                return R.drawable.inst_corazon4;
            case 435:
                return R.drawable.inst_corazon5;
            case 436:
                return R.drawable.inst_corazon6;
            case 437:
                return R.drawable.inst_corazon7;
        }
    }
}
